# Generated by Django 5.1.2 on 2024-10-29 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_failedloginattempt_userblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedloginattempt',
            name='attempt_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 22, 54, 8, 848588)),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='block_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 22, 54, 8, 848815)),
        ),
    ]
