# Generated by Django 5.1.2 on 2024-10-29 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_failedloginattempt_attempt_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedloginattempt',
            name='attempt_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='block_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
