# Generated by Django 5.1.2 on 2024-10-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_failedloginattempt_attempt_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedloginattempt',
            name='attempt_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userblock',
            name='block_time',
            field=models.DateTimeField(),
        ),
    ]
