# Generated by Django 5.1.2 on 2024-11-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_failedloginattempt_attempt_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedloginattempt',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
